### ISSUE TITLE
图片数量

### ISSUE THREAD

**Issue by yaoxh6** [Pengxiao-Wang/Style2Paints_V3#6]
我用了danbooru两万五千张图片做训练，效果非常差，想知道到达图示的效果用多少张图片？
另外直接用百度网盘中的11_Unet_checkpoint.pth.tar无法运行,需要将unet_model.py里面forward函数中的x_inception = self.avg_pool(x_inception)解注释，想问下还有什么需要注意的点吗？

**Comment by Xsz777** [comment]
yaoxh6 可以给个联系方式交流一下么？

**Comment by Xsz777** [comment]
> 我用了danbooru两万五千张图片做训练，效果非常差，想知道到达图示的效果用多少张图片？
> 另外直接用百度网盘中的11_Unet_checkpoint.pth.tar无法运行,需要将unet_model.py里面forward函数中的x_inception = self.avg_pool(x_inception)解注释，想问下还有什么需要注意的点吗？

可以给个联系方式交流一下么？

**Comment by yaoxh6** [comment]
可能是数据集的问题，目前没有问题了，谢谢。



---原始邮件---
发件人: "DLUT_xsz"<notifications@github.com&gt;
发送时间: 2020年4月15日(周三) 中午11:15
收件人: "Pengxiao-Wang/Style2Paints_V3"<Style2Paints_V3@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"yaoxh6"<2879813862@qq.com&gt;;
主题: Re: [Pengxiao-Wang/Style2Paints_V3] 图片数量 (#6)




  
我用了danbooru两万五千张图片做训练，效果非常差，想知道到达图示的效果用多少张图片？
 另外直接用百度网盘中的11_Unet_checkpoint.pth.tar无法运行,需要将unet_model.py里面forward函数中的x_inception = self.avg_pool(x_inception)解注释，想问下还有什么需要注意的点吗？
  
可以给个联系方式交流一下么？

**Comment by wuhan3228873** [comment]
兄dei, 我最近也在看这个， 可以交流一下吗

**Comment by wuhan3228873** [comment]
您好，可以留个联系方式交流一下吗

**Comment by yaoxh6** [comment]
您好，我是神经网络的初学者，还在学习阶段，暂时还没有达到和别人交流的地步，所以就不给联系方式了。



---原始邮件---
发件人: "wuhan3228873"<notifications@github.com&gt;
发送时间: 2020年4月20日(周一) 下午4:47
收件人: "Pengxiao-Wang/Style2Paints_V3"<Style2Paints_V3@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"yaoxh6"<2879813862@qq.com&gt;;
主题: Re: [Pengxiao-Wang/Style2Paints_V3] 图片数量 (#6)




 
您好，可以留个联系方式交流一下吗

**Comment by wuhan3228873** [comment]
您好，我也是初学者 并且是刚刚入门，请教您一个问题，train.py代码里的train,val,sketch,STL的数据我知道是来自Danbooru2019。但是我不太确定他们分别给什么进去。

**Comment by yaoxh6** [comment]
train是训练集，给的是原图。
val是验证集，给的也是原图，总的数据集划分为三份，train、val、test。
sketch是经过KerasSketch程序提取出来的线稿，和train以及val一一对应。
stl是经过模拟处理后的图片，这个在论文中提到，是模拟图片上色问题的处理手段，一共有三个手段，随机提取粘贴，stl，随机涂点，这里是先用stl处理好图片，然后在运行时再使用其他模拟手段。

---原始邮件---
发件人: "wuhan3228873"<notifications@github.com&gt;
发送时间: 2020年4月20日(周一) 下午5:03
收件人: "Pengxiao-Wang/Style2Paints_V3"<Style2Paints_V3@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"yaoxh6"<2879813862@qq.com&gt;;
主题: Re: [Pengxiao-Wang/Style2Paints_V3] 图片数量 (#6)




 
您好，我也是初学者 并且是刚刚入门，请教您一个问题，train.py代码里的train,val,sketch,STL的数据我知道是来自Danbooru2019。但是我不太确定他们分别给什么进去。

**Comment by wuhan3228873** [comment]
好的，万分感谢， train，val，sketch我明白了，  stl我去看下论文。 stl处理过得图片对应的是总数据集吗

**Comment by yaoxh6** [comment]
按照正常思维，stl只需要处理训练时数据即可。目前代码还是有点问题，可以看test.py的代码，
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p&nbsp;=&nbsp;gt_img[j]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gt&nbsp;=&nbsp;Image.open(p).convert('RGB')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;df&nbsp;=&nbsp;Image.open(p).convert('RGB')


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pic,pm&nbsp;=&nbsp;test(Unet,args,gt,sketch,df)




其中df是原图，但是作者自己解释为df : (batch_size, 3, 224, 224) : simulated data which is the input of Inception V1，这部分有点问题，测试的时候应该只需要输入sketch即可，不会要求输入sketch对应的原图。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wuhan3228873"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午5:18
收件人:&nbsp;"Pengxiao-Wang/Style2Paints_V3"<Style2Paints_V3@noreply.github.com&gt;;
抄送:&nbsp;"姚雪辉"<2879813862@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Pengxiao-Wang/Style2Paints_V3] 图片数量 (#6)





 
好的，万分感谢， train，val，sketch我明白了，  stl我去看下论文。 stl处理过得图片对应的是总数据集吗

**Comment by wuhan3228873** [comment]
好的，万分感谢  我明白了

**Comment by Xsz777** [comment]
您好，我也是一名初学者，我的qq是854149960，如果不介意的话，可以加个好友一起学习。



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wuhan3228873"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午4:47
收件人:&nbsp;"Pengxiao-Wang/Style2Paints_V3"<Style2Paints_V3@noreply.github.com&gt;;
抄送:&nbsp;"徐仕卓"<854149960@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Pengxiao-Wang/Style2Paints_V3] 图片数量 (#6)





 
您好，可以留个联系方式交流一下吗
