### ISSUE TITLE
您好，我是初学者，请问训练数据怎么弄的

### ISSUE THREAD

**Issue by wuhan3228873** [Pengxiao-Wang/Style2Paints_V3#7]
'train_path' : 'train data path'#'./your train data path/train',
    'val_path' : 'val data path'#'./your val data path/val',
    'sketch_path' : 'sketch path'#"./your sketch data path/sketch",
    'draft_path' : 'STL path'#"./your STL data path/STL",

我知道训练数据来自Danbooru，但是不知道 train,val,sketch,STL里分别是什么

**Comment by xinzi2018** [comment]
我也有同样的问题
